### ISSUE TITLE
Defense IV/EV definitions missing (v18)

### ISSUE THREAD

**Issue by Snewper16** [TheCrafters001/showdown-to-essentials#1]
**Describe the bug**
Defense IV/EV setting is missing in the v18 converter.

**To Reproduce**
1. Open the 'v18' side of the program.
2. Click on 'Pokemon 1-6' tabs once opened.
3. Look in the 'IVs/EVs' settings for each tab mentioned above, inclusive.
4. Defense IV/EV setting is missing (no error message). Note that all the other IV/EV definitions are present.

**Expected behavior**
There are 6 IVs/EVs to define; the program only has 5.

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Comment by TheCrafters001** [comment]
Yeah, it seems like I made a slight oversight. Sorry about that. A fix is currently in the works :)

**Comment by TheCrafters001** [comment]
Fixed in commit 948bb735174654a98926fbfd863c1f17220d903d - Will be pushed in next update.
