### ISSUE TITLE
[proposal] text add multilanguage; listbox modification suggestion

### ISSUE THREAD

**Issue by Butanee** [TheCrafters001/showdown-to-essentials#15]
This tool is very useful for me, but my native language is not English, and this tool is not very friendly for me, I would like to translate it to Chinese, but I don't know the `.net` language, and I can only modify the text of strings and controls. It's not easy to synchronize the version if I modify it this way, so I would like to get your help.
If it's possible, could you please add a multi-language function, and maybe store all the text in a Txt file, so it's easy to translate for other language speakers?
Also: can you make a list of Pokémon names, moves and Pokémon/trainer props, with fuzzy query support? Ideally, the text displayed in the list should be different from the output text, so that it is easy to be translated by other language speakers.
These proposals may be a bit much, but I hope you can refer to them at your discretion. I'm also learning `.net` and am trying to implement these ideas of mine

**Comment by TheCrafters001** [comment]
Hello! I am glad to hear the tool is helpful for you, and I am glad you wanna try and localize the project! However, due to the nature (and frankly outdated code-base) of the current build (Version 3.2.3), I cannot integrate localization. But, I am working on a new code base (Version 4.0.0 (PR #7)) where I could try to integrate a way for localization. I will try to see what I can do!

**Comment by TheCrafters001** [comment]
Hello! I have started proper work on Multi-Language support, starting with commit 10837214b7da7f4da5046a620ff0349efea08a8d! If you wish to try and implement Chinese, feel free to [fork the v4.0.0 branch](https://github.com/TheCrafters001/showdown-to-essentials/tree/v4) and make new `.zh.resx` files! I recommend using [ResXManager](https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager) to edit the resx files!

**Comment by TheCrafters001** [comment]
I am going to go ahead and close this issue, if you feel the need to re-open it, you may! I have officially merged the v4 branch into main, meaning there is now official support for multiple languages.
