### ISSUE TITLE
Poke Ball custom definitions file

### ISSUE THREAD

**Issue by Snewper16** [TheCrafters001/showdown-to-essentials#2]
**Is your feature request related to a problem? Please describe.**
Definitions allow for 1-25, from Pokeball to Beast Ball, but isn't customizable.

**Describe the solution you'd like**
A. Allow for manual modification of the Pokeball definitions under the 'Pokeball ID Reference' tab.
B. Change drop-down menu for Pokeballs to a text box for custom inputs.
C. Write a custom script for the program that identifies a custom Pokeball ID text file and have it implement it upon startup.

**Describe alternatives you've considered**
One solution I've found is to generate the trainer, then edit manually in the 'trainers' text file, but this would be a time consuming process for many trainers.

**Comment by TheCrafters001** [comment]
Added in commit 90d6ba265dd1b4d7c553628b873a1e884721bfd6
